### ISSUE TITLE
Clean up `gen-ca` example YAMLs

### ISSUE THREAD

**Issue by ZackButcher** [tetratelabs/istio-distro.io#138]
I think the amount of comments in the current versions makes it hard to read/makes it seem more complicated than it is:

```yaml
 providerName: "gcp" 
 providerConfig: 
   gcp: 
     #This will hold the full CA name for the certificate authority you created on GCP 
     casCAName: "projects/{project-id}/locations/{location}/certificateAuthorities/{YourCA}" 
  
 certificateParameters: 
   secretOptions: 
     # Namespace where 'cacerts' Kubernetes secret is created on your target cluster 
     istioCANamespace: "istio-system" 
     # SecretFilePath is the file path used to store the Kubernetes Secret in yaml format 
     secretFilePath: 
     # Force flag when enabled forcefully deletes the `cacerts` secret 
     # in istioNamespace, and creates a new one. 
     force: true 
   caOptions: 
     # ValidityDays represents the number of validity days before the CA expires. 
     validityDays: 365 
     # KeyLength is the length(bits) of Key to be created 
     keyLength: 2048 
     # This is x509.CertificateRequest. Only a few fields are shown below 
     certSigningRequestParams: 
       subject: 
         commonname: "getistio.example.io" 
         country: 
           - "US" 
         locality: 
           - "Sunnyvale" 
         organization: 
           - "Istio" 
         organizationunit: 
           - "engineering" 
       emailaddresses: 
         - "youremail@example.io" 
```

I'd rather we simplify it a bit like:

```yaml
 providerName: "gcp" 
 providerConfig: 
   gcp: 
     #This will hold the full CA name for the certificate authority you created on GCP 
     casCAName: "projects/{project-id}/locations/{location}/certificateAuthorities/{YourCA}" 
  
 certificateParameters: 
   secretOptions: 
     istioCANamespace: "istio-system" # namespace where `cacerts` secrets lives
     force: true # force delete the `cacerts` secret and replace it with this new one
   caOptions: 
     validityDays: 365 # validity days before the CA expires
     keyLength: 2048  # length(bits) of Key to be created 
     certSigningRequestParams: # x509.CertificateRequest; most fields omitted
       subject: 
         commonname: "getistio.example.io" 
         country: 
           - "US" 
         locality: 
           - "Sunnyvale" 
         organization: 
           - "Istio" 
         organizationunit: 
           - "engineering" 
       emailaddresses: 
         - "youremail@example.io" 
```
